acme_bonita:
    resource: "@AcmeBonitaBundle/Resources/config/routing/main.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

acme_bonita_user:
    resource: "@AcmeBonitaBundle/Resources/config/routing/user.yml"
    prefix:   /user

acme_bonita_siniestro:
    resource: "@AcmeBonitaBundle/Resources/config/routing/siniestro.yml"
    prefix:   /siniestro

acme_bonita_objeto_indemnizacion:
    resource: "@AcmeBonitaBundle/Resources/config/routing/objetoIndemnizacion.yml"
    prefix:   /objetoIndemnizacion
