security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN

    access_denied_url: /acceso_prohibido

    providers:
        in_memory:
            memory:
                users:
                    user: { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            #form_login:
            #    provider: fos_userbundle
            #    csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            form_login:
                provider: fos_userbundle
                #csrf_provider: form.csrf_provider
                csrf_provider: security.csrf.token_manager
                check_path:     /user/login_check
                failure_path:   /user/login
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path:   /user/logout
                target: /user/login
            anonymous: ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

      #  login:
      #      pattern:  ^/demo/secured/login$
      #      security: false

      #  secured_area:
       #     pattern:    ^/demo/secured/
        #    form_login:
         #       check_path: _security_check
          #      login_path: _demo_login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }    ##Cualquier usuario puede entrar a las paginas cuyo path contenga /login pero estas siguen las mismas seguridades que todas las demas restringidas
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }  ##Cualquier usuario puede entrar a las paginas que empiecen con /register pero estas siguen las mismas seguridades que todas las demas restringidas
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY } ##Cualquier usuario puede entrar a las paginas que empiecen con /resetting pero estas siguen las mismas seguridades que todas las demas restringidas
       # - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY } ##Cualquier usuario puede entrar a las paginas que empiecen con /logout pero estas siguen las mismas seguridades que todas las demas restringidas
       # - { path: ^/administrador, role: ROLE_ADMIN } ##Solo el usuario ADMIN puede entrar a paginas que comiencen con /admin
        - { path: ^/administrador/borrar, role: ROLE_ADMIN } ##Solo el usuario ADMIN puede entrar a paginas que comiencen con /admin
        - { path: ^/administrador/editar, role: ROLE_ADMIN } ##Solo el usuario ADMIN puede entrar a paginas que comiencen con /admin
        - { path: ^/administrador/actualizar, role: ROLE_ADMIN } ##Solo el usuario ADMIN puede entrar a paginas que comiencen con /admin
        - { path: ^/administrador/usuarios/index, role: ROLE_ADMIN }
        - { path: ^/configuracion, role: ROLE_ADMIN }
        - { path: ^/usuario/profile, role: IS_AUTHENTICATED_FULLY }