# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   # app.form.registration:
#  acme_user.registration.form.type:
#        class: Acme\BuffetBundle\Form\RegistrationType
#        arguments: [%fos_user.model.user.class%]
#        tags:
#            - { name: form.type, alias: app_user_registration }
    #acme_buffet.form.registration.form.type:
    app.form.registration:
        class: Acme\BonitaBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    ##app.form.profile:
      ##  class: Acme\BuffetBundle\Form\ProfileType
        ##tags:
          ##  - { name: form.type, alias: app_user_profile }

    ##appstate:
      ##  class: Acme\BuffetBundle\Extensions\AppState
       ## arguments: [@doctrine.orm.entity_manager]

    #twig.extension.appstate:
     ##   class: Acme\BuffetBundle\Extensions\AppStateExtension
       ## arguments: [@appstate]
       ## tags:
         ##   - { name: twig.extension }