<?php

namespace Acme\BonitaBundle\Repository;

/**
 * ObjetoIndemnizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetoIndemnizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
