<?php

namespace Acme\BonitaBundle\Repository;

/**
 * ObjetoIndemnizacionSiniestroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetoIndemnizacionSiniestroRepository extends \Doctrine\ORM\EntityRepository
{
}
