<?php

namespace Acme\BonitaBundle\Repository;

/**
 * TipoIncidenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoIncidenteRepository extends \Doctrine\ORM\EntityRepository
{
}
