<?php

namespace Acme\BonitaBundle\Repository;

/**
 * TipoEmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEmpleadoRepository extends \Doctrine\ORM\EntityRepository
{
}
