fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_profile_edit: ##En href es fos_user_profile_show para ver tu info y fos_user_profile_edit para editar
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

##fos_user_profile_show:
##    pattern:  /perfil
##    defaults: { _controller: "AcmeBuffetBundle:Profile:show" }

fos_user_register: ##En href es fos_user_registration_register para registrarse y fos_user_security_login para iniciar sesion
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
